[project]
name = "runtime"
version = "0.1"
description = "Competition runtime environment"
requires-python = ">=3.12,<3.13"
dependencies = [
    "accelerate",
    "ctranslate2==4.8.2",
    "datasets",
    "einops",
    "faster-whisper==1.2.1",
    "keras",
    "kenlm==0.3.0",
    "librosa",
    "loguru",
    "mutagen",
    "numpy",
    "pandas",
    "peft",
    "polars>=1.43.2",
    "pyctcdecode==0.5.0",
    "qwen-asr",
    "sacrebleu",
    "sacremoses",
    "scikit-learn",
    "scipy",
    "sentencepiece",
    "soundfile>=0.14.0",
    "tensorflow[and-cuda]",
    "torch",
    "torchaudio",
    "torchcodec",
    "tqdm",
    "transformers",
    "vllm==0.23.0",
]

[project.optional-dependencies]
test = [
    "pytest",
]

[tool.uv]
required-version = ">=0.12.9"
environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]
override-dependencies = [
    "transformers<5",
    { package = { name = "pyctcdecode" }, dependencies = ["numpy>=2.3"] },
]
build-constraint-dependencies = [
    "setuptools==84.0.0",
    "wheel==0.48.0",
    "cmake==4.4.3",
]

[tool.uv.sources]
torch = { index = "pytorch-cu130" }
torchaudio = { index = "pytorch-cu130" }

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true
